pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // 소스코드 체크아웃
                checkout scm
            }
        }

        stage('Clean') {
            steps {
                // gradlew 실행 권한 부여
                sh 'chmod +x ./gradlew'
                // 클린 빌드
                sh './gradlew clean'
            }
        }

        stage('Build Debug') {
            steps {
                // 디버그 APK 빌드
                sh './gradlew assembleDebug'
            }
        }

        stage('Unit Tests') {
            steps {
                // 단위 테스트 실행
                sh './gradlew testDebugUnitTest'
            }
        }
    }

    post {
        success {
            // 빌드 결과물 아카이브
            archiveArtifacts artifacts: '**/build/outputs/apk/debug/*.apk', fingerprint: true
        }
    }
}